import esbuild from "npm:esbuild@0.17.3";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = Deno.args[0] === "production";

const nodeBuiltins = [
	"assert", "buffer", "child_process", "cluster", "console", "constants",
	"crypto", "dgram", "dns", "domain", "events", "fs", "http", "https",
	"module", "net", "os", "path", "punycode", "querystring", "readline",
	"repl", "stream", "string_decoder", "sys", "timers", "tls", "tty",
	"url", "util", "v8", "vm", "worker_threads", "zlib",
];

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	Deno.exit(0);
} else {
	await context.watch();
}
