name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build
        run: deno run -A build.ts production

      - name: Package
        run: zip infobox.zip main.js manifest.json styles.css

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: infobox.zip
